### ISSUE TITLE
Add Legacy Code to Repo

### ISSUE THREAD

**Issue by Mitchell-Conrad-20** [bhageneder/OpticalCapstoneComputerVision2023#37]
Add the legacy code in a Legacy folder to the repo to continue support for the robots not outfitted with computer vision systems. We will need to have this code in order to make modifications for multi-hop. 

Alternatively, have an option in globals/config for legacy mode which will be used on legacy robots.

**Comment by stoneoxmike** [comment]
I don't see this as necessary anymore, not sure what you're still thinking about this

**Comment by Mitchell-Conrad-20** [comment]
We can close this.
