### ISSUE TITLE
NeoPixel Not Supported on Jetson Nano

### ISSUE THREAD

**Issue by Mitchell-Conrad-20** [bhageneder/OpticalCapstoneComputerVision2023#39]
Determine workaround or alternate solution for NeoPixel on Jetson Nano

**Comment by stoneoxmike** [comment]
Option 1: Use adafruit_blinka library to init the GPIO pin in a different way
Option 2: External Arduino/ESP32 controlled via UART/other to control the neopixel
Option 3: Thread with realtime priority using spin loops and usleep

**Comment by Mitchell-Conrad-20** [comment]
Looked into blinka. Sounds like a great solution.
