### ISSUE TITLE
Tracking Terminal Info Dump

### ISSUE THREAD

**Issue by bhageneder** [bhageneder/OpticalCapstoneComputerVision2023#50]
When tracking is enabled, it will output the tracking status, stracking id, and frames into the terminal. This would be helpful when debugging but it annoying and not necessary when trying to view other information. There needs to be a way to snuff the info when not desired. 

Reference Image:
![20240301_115157](https://github.com/bhageneder/OpticalCapstoneComputerVision2023/assets/98890401/133cab65-8010-46b7-a5e0-ed62cf702da6)

**Comment by stoneoxmike** [comment]
Fixed with changes to LogLevel via jetson_utils logging
