### ISSUE TITLE
Camera Concat Incorrect

### ISSUE THREAD

**Issue by bhageneder** [bhageneder/OpticalCapstoneComputerVision2023#8]
Under certain conditions (unknown as of 9PM 7/10) the camera frames get concated in the wrong order resulting in improper images. I.E going all the right on one frame moves to the further point left on the previous.

**Comment by Mitchell-Conrad-20** [comment]
@bhageneder Do you know if this has been addressed? I don't think it has been. If not, this is likely something we should address using a config file. Should only take a few minutes.

**Comment by Mitchell-Conrad-20** [comment]
@bhageneder this has been addressed. Individual nodes configure the camera setup using the config file.
